# Docker Compose for OpenSearch with Extensions (Bridge Network)
services:
  opensearch-node1:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      # CRITICAL: Enable extensions support
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dopensearch.experimental.feature.extensions.enabled=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-SecurePassword123!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200  # REST API
      - 9600:9600  # Performance Analyzer
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -ku admin:$$OPENSEARCH_INITIAL_ADMIN_PASSWORD https://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 60s

  opensearch-node2:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      # CRITICAL: Enable extensions support
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dopensearch.experimental.feature.extensions.enabled=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-SecurePassword123!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
    driver: bridge

# Extension Communication Notes:
# - Your extension on host localhost:1234 can communicate with OpenSearch via:
#   - Node 1: https://localhost:9200 (mapped from container)
#   - Node 2: https://opensearch-node2:9200 (internal only)
# - Use the bridge network for stable container-to-container communication
# - Extension registration should target https://localhost:9200

# Usage Commands:
# 1. Set password: export OPENSEARCH_INITIAL_ADMIN_PASSWORD=Anubhav@321
# 2. Start cluster: docker-compose -f docker-compose-host-extension.yml up -d
# 3. Verify cluster: curl -k -u admin:Anubhav@321 https://localhost:9200/_cluster/health
# 4. Start your extension: cargo run
# 5. Register extension: just loadext_secure
